# Generated by Django 3.2 on 2024-10-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='delivery',
        ),
    ]
